### ISSUE TITLE
Cant find path

### ISSUE THREAD

**Issue by sk4termmje** [dropout1337/TikTok-Share-Bot#10]
main.go:16:2: cannot find package "github.com/admin100/util/console" in any of:
        D:\Program Files\Go\src\github.com\admin100\util\console (from $GOROOT)
        C:\Users\User\go\src\github.com\admin100\util\console (from $GOPATH)
main.go:17:2: cannot find package "github.com/corpix/uarand" in any of:
        D:\Program Files\Go\src\github.com\corpix\uarand (from $GOROOT)
        C:\Users\User\go\src\github.com\corpix\uarand (from $GOPATH)

**Comment by dropout1337** [comment]
https://github.com/dropout1337/TikTok-Share-Bot/issues/7
