### ISSUE TITLE
Crashing after starting

### ISSUE THREAD

**Issue by Buenass7300** [dropout1337/TikTok-Share-Bot#6]
[10:48:06] Successfully started 500 threads.panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xa90df1]

goroutine 83 [running]:
main.share()
        C:/Users/test/Desktop/GO/TikTok Share Bot/main.go:102 +0x2d1
created by main.main
        C:/Users/test/Desktop/GO/TikTok Share Bot/main.go:53 +0x30d
Every time i get it to start it works for a few seconds and then crashes.

**Comment by dropout1337** [comment]
dont use hella threads, ur memory is being capped therefor the program crashes.
