### ISSUE TITLE
error while share

### ISSUE THREAD

**Issue by oripddtf34ertw** [dropout1337/TikTok-Share-Bot#9]
goroutine 3869 [running]:
main.share()
        C:/Users/lil nig/Desktop/main/main.go:103 +0x2d1
created by main.main
        C:/Users/lil nig/Desktop/main/main.go:53 +0x2f1
exit status 2

I mean I did to many threads but if you can fix that, that will be great

**Comment by dropout1337** [comment]
dont use hella threads, ur memory is being capped therefor the program crashes.
